# -*- mode: python ; coding: utf-8 -*-


block_cipher = None


a = Analysis(['program.py'],
             pathex=['C:\\Users\\vnich\\PycharmProjects\\Parser-Shop-Metro'],
             binaries=[('convertor/convertor_json.py', '.'),
                        ('convertor/from_db_to_excel.py', '.'),
                        ('convertor/from_string_to_number.py', '.'),
                        ('convertor/__init__.py', '.'),
                        ('database/additional_images.py', '.'),
                        ('database/ad_metro.py', '.'),
                        ('database/article_images.py', '.'),
                        ('database/db_session.py', '.'),
                        ('database/__all_models.py', '.'),
                        ('database/__init__.py', '.'),
                        ('parser_metro/parser.py', '.'),
                        ('parser_metro/parsercatalog.py', '.'),
                        ('parser_metro/parserproduct.py', '.'),
                        ('parser_metro/__init__.py', '.'),
                        ('parser_metro/catalog/catalog.py', '.'),
                        ('parser_metro/catalog/catalogfactory.py', '.'),
                        ('parser_metro/catalog/__init__.py', '.'),
                        ('parser_metro/catalog/max_page/isearchmaxpage.py', '.'),
                        ('parser_metro/catalog/max_page/searchmaxpage.py', '.'),
                        ('parser_metro/catalog/max_page/searchmaxpageerror.py', '.'),
                        ('parser_metro/catalog/max_page/__init__.py', '.'),
                        ('parser_metro/catalog/product_lists/iproductlist.py', '.'),
                        ('parser_metro/catalog/product_lists/iurlproduct.py', '.'),
                        ('parser_metro/catalog/product_lists/productlist.py', '.'),
                        ('parser_metro/catalog/product_lists/productlisterror.py', '.'),
                        ('parser_metro/catalog/product_lists/urlproduct.py', '.'),
                        ('parser_metro/catalog/product_lists/urlproducterror.py', '.'),
                        ('parser_metro/catalog/product_lists/__init__.py', '.'),
                        ('parser_metro/meal/additionalimages.py', '.'),
                        ('parser_metro/meal/annotation.py', '.'),
                        ('parser_metro/meal/articleimages.py', '.'),
                        ('parser_metro/meal/articlenumber.py', '.'),
                        ('parser_metro/meal/brand.py', '.'),
                        ('parser_metro/meal/expirationdate.py', '.'),
                        ('parser_metro/meal/informationspecificationkey.py', '.'),
                        ('parser_metro/meal/iparameter.py', '.'),
                        ('parser_metro/meal/mainimage.py', '.'),
                        ('parser_metro/meal/meal.py', '.'),
                        ('parser_metro/meal/name.py', '.'),
                        ('parser_metro/meal/packingparameters.py', '.'),
                        ('parser_metro/meal/price.py', '.'),
                        ('parser_metro/meal/pricewithoutdiscount.py', '.'),
                        ('parser_metro/meal/weight.py', '.'),
                        ('parser_metro/meal/__init__.py', '.'),
                        ('parser_metro/product/product.py', '.'),
                        ('parser_metro/product/productfactory.py', '.'),
                        ('parser_metro/product/__init__.py', '.'),
                        ('parser_metro/product/block_base/blockbase.py', '.'),
                        ('parser_metro/product/block_base/blockbaseerror.py', '.'),
                        ('parser_metro/product/block_base/iblockbase.py', '.'),
                        ('parser_metro/product/block_images/blockimages.py', '.'),
                        ('parser_metro/product/block_images/blockimageserror.py', '.'),
                        ('parser_metro/product/block_images/iblockimages.py', '.'),
                        ('parser_metro/product/block_price/blockprice.py', '.'),
                        ('parser_metro/product/block_price/blockpriceerror.py', '.'),
                        ('parser_metro/product/block_price/iblockprice.py', '.'),
                        ('parser_metro/product/block_specifications/blockspecifications.py', '.'),
                        ('parser_metro/product/block_specifications/blockspecificationserror.py', '.'),
                        ('parser_metro/product/block_specifications/iblockspecifications.py', '.'),
                        ('recipient_from_server/chromewebdriver.py', '.'),
                        ('recipient_from_server/iproxy.py', '.'),
                        ('recipient_from_server/iwebdriver.py', '.'),
                        ('recipient_from_server/proxy.py', '.'),
                        ('recipient_from_server/__init__.py', '.'),
                        ('parameters.py', '.'),
                        ('program.py', '.'),],
             datas=[],
             hiddenimports=["selenium", "bs4", "xlsxwriter", "os", "pyqt5", "sqlalchemy", "lxml"],
             hookspath=[],
             hooksconfig={},
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)

exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,  
          [],
          name='main',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          upx_exclude=[],
          runtime_tmpdir=None,
          console=True,
          disable_windowed_traceback=False,
          target_arch=None,
          codesign_identity=None,
          entitlements_file=None )
